[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Ryan Day <rynday@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
